copper-project/copper-rs

cu29_export/Cargo.toml, cu29_export/src/lib.rs
This is a quick fix for #8 
As this is a test I think it is just ok to work around the change issue.
=> export: fix tests changing committed files

cu29_log_runtime/Cargo.toml, cu29_log_runtime/tests/end2end.rs
=> Fix circular dep for tests in cu29_log_runtime

cu29/src/curuntime.rs, cu29_derive/src/lib.rs
on the back of adding batches, this adds the notion of loops in the runtime plan.
=> runtime loops: Part 1: added a notion of loop for the runtime plan

cu29/Cargo.toml, cu29/src/config.rs, cu29/src/monitoring.rs
It allows to build real time statistics with a specialization for CuDurations out of Copper's engine.
=> │First implementation of cumulative stats

cu29/src/config.rs, cu29/src/copperlist.rs, cu29/src/curuntime.rs, cu29/src/cutask.rs, cu29/src/monitoring.rs, cu29_clock/src/lib.rs, cu29_derive/src/lib.rs, cu29_export/src/lib.rs, cu29_traits/src/lib.rs, examples/cu_caterpillar/src/logreader.rs, examples/cu_monitoring/src/main.rs, examples/cu_rp_balancebot/src/logreader.rs
it is tested with the cu-monitor project
=> Monitor part 2: the backend

components/monitors/cu_consolemon/src/lib.rs, components/sinks/cu_rp_sn754410/tests/sn754410_tester.rs, components/sources/cu_ads7883/tests/ads7883_tester.rs, components/sources/cu_rp_encoder/src/lib.rs, components/sources/cu_wt901/tests/wt901_tester.rs, core/cu29/src/config.rs, core/cu29/src/curuntime.rs, core/cu29/src/cutask.rs, core/cu29/src/lib.rs, core/cu29/src/simulation.rs, core/cu29_derive/Cargo.toml, core/cu29_derive/src/lib.rs, core/cu29_derive/src/utils.rs, core/cu29_helpers/src/lib.rs, core/cu29_log_runtime/tests/end2end.rs, examples/cu_caterpillar/src/main.rs, examples/cu_monitoring/src/main.rs, examples/cu_multisources/src/main.rs, examples/cu_rp_balancebot/src/main.rs, templates/cu_full/src/main.rs
Those are the hooks in the API to be able to implement both Sim / Resim and part of the deterministic replay.
=> cu29: sim bindings

components/sources/cu_vlp16/src/lib.rs, core/cu29_soa_derive/src/lib.rs, core/cu29_soa_derive/tests/proctest.rs
-Cleaned up the generation
-Removed the Add/Sub operations.
=> Fix ups for SOA

Cargo.toml, components/sinks/cu_iceoryx2_sink/Cargo.toml, components/sinks/cu_iceoryx2_sink/README.md, components/sinks/cu_iceoryx2_sink/build.rs, components/sinks/cu_iceoryx2_sink/src/lib.rs, components/sinks/cu_rp_gpio/src/lib.rs, components/sources/cu_iceoryx2_src/Cargo.toml, components/sources/cu_iceoryx2_src/README.md, components/sources/cu_iceoryx2_src/build.rs, components/sources/cu_iceoryx2_src/src/lib.rs, core/cu29/src/cutask.rs, examples/cu_caterpillar/src/lib.rs, examples/cu_iceoryx2/Cargo.toml, examples/cu_iceoryx2/README.md, examples/cu_iceoryx2/build.rs, examples/cu_iceoryx2/downstream.ron, examples/cu_iceoryx2/src/bin/downstream.rs, examples/cu_iceoryx2/src/bin/upstream.rs, examples/cu_iceoryx2/src/lib.rs, examples/cu_iceoryx2/upstream.ron
With a source, a sink and a full example.
=> Iceoryx2 support.

core/cu29/src/cutask.rs
Added a proper unit test to catch this.
=> FIX: CuCompactStr was not bincode/ser bincode/de correctly.

examples/cu_rp_balancebot/src/sim.rs
The root cause was that by default bevy/wgpu tries out a bunch of backends and puts the graphic stack in a weird state.
By forcing the backend it ends the process cleanly.
=> Fixes #117: coredump on exit for balancebot-sim

Cargo.toml, core/cu29_derive/src/lib.rs, examples/cu_caterpillar/Cargo.toml, examples/cu_iceoryx2/Cargo.toml, examples/cu_rp_balancebot/Cargo.toml, examples/cu_rp_balancebot/copperconfig.ron, examples/cu_rp_balancebot/src/logreader.rs, examples/cu_rp_balancebot/src/resim.rs, examples/cu_rp_balancebot/src/sim.rs
Ok this works.
This is just a very manual example that will serve as a blueprint to make the UX better.
=> WIP: Builds a Resim out for an example and the sim support.

core/cu29_soa_derive/src/lib.rs, core/cu29_soa_derive/tests/proctest.rs
It makes it easier to use for point by point algorithms.
=> Generates an iterator for the SOA

.github/workflows/general.yml, .gitignore, templates/cu_full/Cargo.toml.template, templates/cu_full/cargo-generate.toml, templates/cu_full/init.rhai, templates/cu_full/rename_cargo_toml.rhai, templates/cu_full/src/logreader.rs, templates/cu_full/src/main.rs, templates/cu_full/src/tasks.rs
Now it allows the user to select against what the project is generated from (git, crates or local)
This allows the test to be independent of master
=> Improving the project template.

core/cu29_export/Cargo.toml, core/cu29_export/src/lib.rs
=> Update `pyo3` crate to "0.23.3".

examples/cu_rp_balancebot/Cargo.toml
=> Enable "x11" feature.

core/cu29_derive/src/lib.rs
=> At least allocate a CuList size of a section in the logger.

core/cu29_clock/src/lib.rs, core/cu29_derive/src/lib.rs, core/cu29_derive/src/utils.rs, core/cu29_export/src/lib.rs, core/cu29_log/src/lib.rs, core/cu29_log_derive/src/index.rs, core/cu29_log_runtime/src/lib.rs, core/cu29_runtime/src/config.rs, core/cu29_runtime/src/payload.rs, core/cu29_unifiedlog/src/lib.rs
=> style: simplify some statements for readability

.github/workflows/general.yml, core/cu29_runtime/src/copperlist.rs
Also make the build fail on it (on linux only to speed it up)
=> switch to a way more tight clippy

core/cu29_runtime/Cargo.toml, core/cu29_runtime/src/lib.rs, core/cu29_runtime/src/log.rs, core/cu29_runtime/src/monitoring.rs, core/cu29_runtime/src/pool.rs
(this is a split PR from the working branch)
=> Creates a Host side memory pool with handles usable in Copper messages

components/payloads/cu_sensor_payloads/Cargo.toml, components/payloads/cu_sensor_payloads/src/image.rs
=> Added Kornia image support

components/payloads/cu_sensor_payloads/Cargo.toml
added new fresh version: https://crates.io/crates/kornia
=> update kornia image version 0.1.8

core/cu29_runtime/src/config.rs, core/cu29_runtime/src/curuntime.rs, examples/cu_caterpillar/copperconfig.ron
=> Make config entry to disable the logging in the ron file

.github/workflows/general.yml
=> [FEAT] update CI: add cache

components/monitors/cu_consolemon/src/lib.rs, examples/cu_caterpillar/Cargo.toml
Do not gobble events when it is not the one you are not interested in.
Fixing #236
=> Consolemon switching screen 

components/sources/cu_ads7883/src/lib.rs
https://github.com/copper-project/copper-rs/actions/runs/13370066528/job/37336434923
=> (cu_ads7883) beta clippy

Cargo.toml, components/monitors/cu_consolemon/Cargo.toml, components/sources/cu_hesai/Cargo.toml, components/sources/cu_livox/Cargo.toml, core/cu29_runtime/Cargo.toml, patches/arrow-arith/Cargo.toml, patches/arrow-arith/src/aggregate.rs, patches/arrow-arith/src/arithmetic.rs, patches/arrow-arith/src/arity.rs, patches/arrow-arith/src/bitwise.rs, patches/arrow-arith/src/boolean.rs, patches/arrow-arith/src/lib.rs, patches/arrow-arith/src/numeric.rs, patches/arrow-arith/src/temporal.rs
cudarc completely depends on the cuda version you have installed locally so even minor updates can add new cuda support.
This is what happened to me and I started to have random compilation results across various Copper compilations.
=> Fully pin cudarc + other indirect deps nightmare 

Cargo.toml, components/payloads/cu_sensor_payloads/src/image.rs, components/sources/cu_gstreamer/src/lib.rs, components/tasks/cu_dynthreshold/Cargo.toml, components/tasks/cu_dynthreshold/README.md, components/tasks/cu_dynthreshold/src/lib.rs
This is a new algorithm, I went through a pass of optimization on the youtube channel. I made it a little bit parameterizable(?).
=> Ported the Dynamic Threshold to Copper

Cargo.toml, components/payloads/cu_spatial_payloads/Cargo.toml, components/payloads/cu_spatial_payloads/src/lib.rs, patches/arrow-arith/src/temporal.rs
generalized it to 32 and 64 bits.
With a faer, nalgebra and glam triple compatibility support.
=> Adding Transform3D / Pose as a standard Copper message payload.

Cargo.toml, components/payloads/cu_sensor_payloads/src/image.rs, components/payloads/cu_sensor_payloads/src/pointcloud.rs, components/sinks/cu_lewansoul/src/lib.rs, components/sinks/cu_msp_sink/src/lib.rs, components/sources/cu_gstreamer/src/lib.rs, components/sources/cu_msp_src/src/lib.rs, components/sources/cu_wt901/src/lib.rs, components/tasks/cu_apriltag/src/lib.rs, core/cu29_clock/src/lib.rs, core/cu29_derive/src/lib.rs, core/cu29_log/src/lib.rs, core/cu29_runtime/src/cutask.rs, core/cu29_runtime/src/payload.rs, core/cu29_runtime/src/pool.rs, core/cu29_soa_derive/src/lib.rs, core/cu29_traits/src/lib.rs, core/cu29_value/src/bdec.rs, examples/cu_monitoring/src/main.rs
Note: The pinning on 2.0.0-rc3 doesn't prevent 2.0.0
This solves: #253
=> Huge 2.0.0-rc3 to 2.0.0 emergency bincode regression.

components/sources/cu_gstreamer/src/lib.rs
Ideally we want to get it from the streamer clock (which is kind of convoluted so we'll do it later)
=> Added an approximate TOV from the gtreamer pipeline + a TODO

components/common/cu_msp_lib/src/structs.rs
bit by bit adding useful commands.
=> Added Raw RC to the high level layer for MSP

components/sinks/cu_lewansoul/src/lib.rs, core/cu29_clock/src/lib.rs, core/cu29_unifiedlog/src/lib.rs
relavent weekly CI: https://github.com/copper-project/copper-rs/actions/runs/14309008650
=> [CHORE] (cu_lewansoul, cu29_clock, cu29_unifiedlog) fix beta clippy

components/sources/cu_v4l/src/v4lstream.rs
https://github.com/copper-project/copper-rs/actions/runs/14445457350/job/40504913726
=> [FIX] (cu_v4l) beta clippy

templates/README.md, templates/cu_full/Cargo.toml.template, templates/cu_full/src/logreader.rs
Address https://github.com/copper-project/copper-rs/issues/234
=> [FEAT] logreader feat for template

components/sinks/cu_iceoryx2_sink/src/lib.rs, components/sources/cu_iceoryx2_src/src/lib.rs
1. Fix `stop` in `cu_iceoryx2_sink`.
2. Improve logging of `cu_iceoryx2_sink` and `cu_iceoryx2_src` by adding `service_name` into log. It is important to separate the info between different service for debugging.
=> [FIX] (iceoryx2) improve logging

components/payloads/cu_spatial_payloads/Cargo.toml
bump faer from v0.21.9 to v0.22.4: https://github.com/sarah-quinones/faer-rs/compare/faer-v0.21.9...faer-v0.22.4
=> [CHORE] Bump faer to v0.22.4

.config/deny.toml
Tracking Issue: https://github.com/copper-project/copper-rs/issues/314
=> [FIX] ignore RUSTSEC-2023-0071 and wait for rsa crate to fix it

README.md, core/cu29_derive/src/lib.rs, core/cu29_derive/tests/compile_fail/copper_runtime/invalid_config_file.stderr, core/cu29_derive/tests/compile_fail/cu_msg/invalid_config_file.stderr, core/cu29_derive/tests/compile_fail/cu_msg/non_existent_id.stderr, core/cu29_runtime/src/config.rs, core/cu29_runtime/tests/includes.rs, core/cu29_runtime/tests/modular_config.rs, doc/modular_config.md, examples/modular_config_example/README.md, examples/modular_config_example/base.ron, examples/modular_config_example/main_config.ron, examples/modular_config_example/motors.ron
This PR implements a modular configuration system for Copper-rs that allows splitting large configurations into reusable components. The implementation enables parameter substitution, file inclusion, and hierarchicalcomposition - addressing a key roadmap item.
- File includes with relative/absolute paths
- Parameter substitution with {{parameter_name}} syntax
~~- Hierarchical inclusion with circular dependency detection~~ (removed to support template-based configuration)
- Well-defined merging rules for configuration components
The `modular_config_example` directory provides a clear demonstration of the feature in action, showing how to:
- Create reusable configuration templates
- Apply different parameters to the same template
- Organize configuration into logical components
=> [FEAT] Implement modular configuration

support/nix/README.md, support/nix/flake.nix, support/nix/shell.nix
- non-cuda option
```
cd support/nix
nix-shell
cargo build --workspace --features macro_debug,mock,perfui,image,kornia,python,gst,faer,nalgebra,glam,debug_pane,bincode
```
- cuda option (need a lot of disk space)
```
cd support/nix
nix-shell --arg withCuda true
cargo build --workspace --all-features
```
=> [FEAT] nix setup

components/monitors/cu_consolemon/src/lib.rs, core/cu29_derive/src/lib.rs, core/cu29_runtime/src/config.rs, core/cu29_runtime/src/curuntime.rs, core/cu29_runtime/tests/includes.rs, core/cu29_runtime/tests/modular_config.rs, examples/cu_config_gen/src/main.rs, examples/cu_config_variation/src/main.rs
This avoids the mix up between Config concerns and Task Graphs.
This allows us to cleanup the root instantiations in the runtime to start the right mission.
=> Moved the graph functions to CuGraph.

core/cu29_derive/src/lib.rs
This should be enough for the user to be able to manually switch from one mission to another by stopping one and starting the other.
We need to think about how we can generate a some high level control for that as a next step.
=> Generates all the missions, still defaults to default.

Cargo.toml, components/tasks/cu_ratelimit/Cargo.toml, components/tasks/cu_ratelimit/README.md, components/tasks/cu_ratelimit/build.rs, components/tasks/cu_ratelimit/src/lib.rs
=> CuRateLimit: New task to simply rate limit messages.

examples/cu_rp_balancebot/Cargo.toml
=> [CHORE] bump iyes_perf_ui to 0.5.0

core/cu29/src/lib.rs, core/cu29_derive/src/lib.rs, core/cu29_runtime/src/app.rs, core/cu29_runtime/src/lib.rs, core/cu29_runtime/src/simulation.rs, examples/cu_rp_balancebot/Cargo.toml, examples/cu_rp_balancebot/src/resim.rs, examples/cu_rp_balancebot/src/sim.rs
This allows to manage a set of copper applications generated by the new missions feature from a common tratir.
=> Introduces a common trait for Copper Applications.

.gitignore, examples/ros_zenoh_caterpillar/Dockerfile, examples/ros_zenoh_caterpillar/README.txt, examples/ros_zenoh_caterpillar/run.sh, examples/ros_zenoh_caterpillar/src/gpio_caterpillar/CMakeLists.txt, examples/ros_zenoh_caterpillar/src/gpio_caterpillar/package.xml, examples/ros_zenoh_caterpillar/src/gpio_caterpillar/src/actuation_node.cpp, examples/ros_zenoh_caterpillar/src/gpio_caterpillar/src/flip_node.cpp, examples/ros_zenoh_caterpillar/src/gpio_caterpillar/src/propagate_node.cpp
This is to add to the collection of comparative benchmark
=> Zenoh version of the ROS caterpillar

core/cu29_runtime/src/config.rs, core/cu29_runtime/src/curuntime.rs
It defaults to 100 copperlists.
=> Added config for the keyframe interval.

core/cu29_derive/src/lib.rs, core/cu29_export/src/lib.rs, core/cu29_runtime/src/curuntime.rs, core/cu29_unifiedlog/src/lib.rs, examples/cu_caterpillar/copperconfig.ron, examples/cu_caterpillar/src/resim.rs, examples/cu_caterpillar/src/tasks.rs, examples/cu_missions/Cargo.toml, examples/cu_rp_balancebot/src/resim.rs
This implementation was missing.
=> [IMPR] Added Keyframe reader & end of processing.

Cargo.toml, core/cu29_unifiedlog/src/lib.rs, examples/cu_dorabench/Cargo.toml, examples/cu_dorabench/README.md, examples/cu_dorabench/build.rs, examples/cu_dorabench/copperconfig.ron, examples/cu_dorabench/src/lib.rs, examples/cu_dorabench/src/logreader.rs, examples/cu_dorabench/src/main.rs, examples/cu_dorabench/src/tasks.rs
If you happen to be able to actually run theirs that would be even better.
=> This is a quick benchmark for an apple to apple comparison with dora-rs

components/sinks/cu_iceoryx2_sink/src/lib.rs, components/sources/cu_hesai/src/lib.rs, components/sources/cu_iceoryx2_src/src/lib.rs, components/sources/cu_livox/src/lib.rs, components/sources/cu_vlp16/src/lib.rs, components/tasks/cu_aligner/src/buffers.rs, components/tasks/cu_aligner/src/lib.rs, components/tasks/cu_apriltag/src/lib.rs, components/tasks/cu_dynthreshold/src/cu_dynthreshold_impl.rs, components/tasks/cu_ratelimit/src/lib.rs, core/cu29_derive/src/lib.rs, core/cu29_runtime/src/cutask.rs, core/cu29_runtime/src/simulation.rs, core/cu29_traits/src/lib.rs, examples/cu_multisources/src/tasks.rs
This is a follow up towards generalizing CuMsg into a more Data/TOV/Metadata combo that can be used all over the place in a robotics stack.
=> Parameterized Metadata for CuStampedData

Cargo.toml, core/cu29_derive/src/lib.rs, core/cu29_runtime/src/config.rs, examples/cu_nologging_tasks/Cargo.toml, examples/cu_nologging_tasks/build.rs, examples/cu_nologging_tasks/copperconfig.ron, examples/cu_nologging_tasks/src/logreader.rs, examples/cu_nologging_tasks/src/main.rs
1. Added a logging { enabled = false } entry to the ron file
2. Generates the payload clears of the matching tasks on the runtime generation
=> Adds a way to disable logging for some tasks.

.github/workflows/general.yml, .github/workflows/weekly.yml
1. disable windows runner for weekly CI
2. add the following configuration for `Jimver/cuda-toolkit`
```
use-github-cache: false
use-local-cache: false
```
=> [FIX] weekly CI by disabling windows runner

core/cu29_derive/src/lib.rs
=> Fixes the run_in_sim regression on sources.

Cargo.toml, core/cu29/Cargo.toml, core/cu29/src/lib.rs, core/cu29_value/Cargo.toml
This is really small for the crate deps on crates.io
=> cu29 base port to no-std
