- README.md
- cu29/src/lib.rs
Fixes some typos and adds relative markdown links where possible. It's easier to navigate around docs locally when markdown links are relative.
> Minor doc fixes

- cu29_derive/Cargo.toml
- cu29_derive/src/lib.rs
This diff is kinda nasty to look at. It's easier to see what I changed when you look at the source by itself.
**What?** 
We were iterating over `all_tasks_types` 5 times to create all the different node arrays. While there is nothing technically wrong with that, it's not the cleanest in my opinion. So I changed it to create all the node arrays in a single iteration of `all_tasks_types`. 
This required using `itertools::multiunzip` which means I had to bring `itertools` in to the repo. But that's good. It's super powerful and we will inevitably use more from it.
**Why?**
Keeping it rusty :call_me_hand: 
**Testing:**
I did my best to verify that this change wouldn't change the output. ie that it is a pure refactor. But if you are able to check that too it would make me feel better since I …
> Refactor: Build all node arrays in one iteration

- Cargo.toml
- cu29/src/curuntime.rs
- cu29_export/Cargo.toml
- cu29_export/build.rs
- cu29_export/src/lib.rs
- cu29_log/Cargo.toml
- cu29_log/src/lib.rs
- cu29_log_runtime/Cargo.toml
- cu29_log_runtime/src/lib.rs
- cu29_traits/src/lib.rs
- cu29_unifiedlog/src/lib.rs
- examples/cu_standalone_structlog/Cargo.toml
- examples/cu_standalone_structlog/build.rs
- examples/cu_standalone_structlog/profile_cu.sh
- examples/cu_standalone_structlog/profile_st.sh
- examples/cu_standalone_structlog/readlog.py
- examples/cu_standalone_structlog/src/standardlog_perf.rs
- examples/cu_standalone_structlog/src/structlog_perf.rs
Notable change: I completely removed the queue in the runtime as the overhead was larger than a simple unbuffered mutex. 
I also build a quick benchmark to compare the speed with the more traditional Rust text logging.
```
sal ➜  cu_standalone_structlog (gbin/structlog_optim) ✗ source back2back.sh
Compiling cu_standalone_structlog v0.2.1 (/home/gbin/projects/copper/copper-rs/examples/cu_standalone_structlog)
Finished `release` profile [optimized] target(s) in 1.92s
Running `/home/gbin/projects/copper/copper-rs/target/release/standardlog_perf`
Total time: 34.220 s in ./logfile.txt
.rw-r--r-- gbin gbin 101 MB Sat Aug 10 10:45:55 2024  logfile.txt
Compiling cu_standalone_structlog v0.2.1 (/home/gbin/projects/copper/copper-rs/examples/cu_standalone_structlog)
CLog: …
```
> log: Simplified and optimized the structlog

- cu29/build.rs
- cu29_log/src/lib.rs
- cu29_log_derive/build.rs
- cu29_log_runtime/build.rs
- drivers/cu_rp_gpio/build.rs
- drivers/cu_vlp16/build.rs
- drivers/cu_wt901/build.rs
- drivers/cu_wt901_tester/build.rs
- examples/cu_caterpillar/build.rs
- examples/cu_standalone_structlog/build.rs
- templates/cu_full/build.rs
This is to be sure we can decouple the compilation from the index generation. Like this the user can drop the build.rs and directly set a directory for example compatible with a distributed compilation system on a shared drive.
> cu29_log: use a more specific env var

- cu29_export/src/lib.rs
- cu29_unifiedlog/src/lib.rs
This should fix both #1 and #22
> unified_logger: dual slab logging, no more remap/resize

- .github/workflows/general.yml
- Cargo.toml
Like that the picky crates that are drivers etc, only gets compiled on demand.
> build: split the core from the driver/examples for macos

- .github/workflows/general.yml
- cu29_export/src/lib.rs
- cu29_helpers/src/lib.rs
- cu29_unifiedlog/src/lib.rs
- examples/cu_caterpillar/src/main.rs
Like we did on the writer side, we need to adapt the reading side to accommodate for "slab" files.
And a gazillion bug got discovered and squashed doing the end to end testing.
> unified_logger: Refactoring to have a slab reader side too

- cu29_unifiedlog/src/lib.rs
There was an unnecessary race condition on the drop of a SectionHandler and the actual update of the section header.
As we explicitly flush them anyway and semantically they are equivalent as closing them, I just moved the header update to the spot right before flushing them.
> Fix change after section flush coredump

- cu29_unifiedlog/src/lib.rs
When a stream is closed a section doesn't rewrite itself at drop so it need to be done a the drop of the stream.
> log stream: reput the flush at the stream level

- cu29_export/src/lib.rs
- cu29_helpers/src/lib.rs
- cu29_intern_strs/src/lib.rs
- cu29_log/src/lib.rs
- cu29_log_derive/src/lib.rs
- cu29_log_runtime/src/lib.rs
- examples/cu_standalone_structlog/src/structlog_perf.rs
I encountered a bug with the current implementation when you want to use the standard logger on top of the structed one in a debug build on ARM. This completely removes the need to copy the index with the executable when you just want to debug something quick. 
This fixes #31 and generally improves the user experience.
> struct_log: removed the need to have the index file in debug mode

- cu29_derive/src/lib.rs
- cu29_log_derive/src/index.rs
We need to do that because the compiler has a json output option that gets corrupted otherwise. This fixes #34
> compilation: moves the compilation feedback from std to err

- cu29/src/copperlist.rs
- cu29/src/curuntime.rs
- cu29_derive/src/lib.rs
- cu29_export/src/lib.rs
- examples/cu_caterpillar/src/logreader.rs
- examples/cu_monitoring/src/main.rs
- examples/cu_rp_balancebot/src/logreader.rs
- templates/cu_full/src/logreader.rs
It solves 3 problems:
1. now we can track the latency truely end to end without the hack I implemented previously forcing me to have the input for the sinks as writeable. Now it generates a virtual end msg that is just the metadata for the sink.
2. it allows monitoring to work with sinks
3. doing that I hit a serious limitation with the tuple that triggered a refactoring of the CopperLists. It is 2 fold: one, all the blanket traits like Debug are implemented up to tuples of 12 elements, and the second issue, any tuple is considered a foreign type so if the trait is not in the crate I cannot implement them. The solution is to have a type wrapper.
While at it, I renames cl.payload to cl.msgs so it makes the hierarcy crystal clear:
CL - Msg - Payload
> Sink virtual output + Added wrapper around msgs instead of tuple.

- support/docker/run_docker.sh
It appears that the Docker mount path required an update following the [reorganization](https://github.com/copper-project/copper-rs/commit/55d02fd26063e59f5fc14792cf2a93b4ca221e39).
Tested locally.
> [Docker] Update 'run_docker.sh' to mount the entire workspace directory

- .gitignore
It seems that `.copper` extension is reserved for the logger. In this PR, we add it to the gitignore list to prevent annoying mistakes when committing.
> Add `*.copper` to gitignore

- components/monitors/cu_consolemon/src/lib.rs
- core/cu29/src/config.rs
- core/cu29/src/curuntime.rs
- core/cu29/src/monitoring.rs
- core/cu29_derive/src/lib.rs
- examples/cu_monitoring/src/main.rs
- examples/cu_rp_balancebot/copperconfig.ron
- examples/cu_rp_balancebot/src/sim.rs
- examples/cu_rp_balancebot/src/world/mod.rs
Other changes:
Now the monitoring gets the full config.
This solves #77
> Embed the default config to Copper's executable.

- core/cu29/src/simulation.rs
- core/cu29_derive/src/lib.rs
- examples/cu_rp_balancebot/src/sim.rs
In Sim there was no was to simulate a task erroring out. This fixes this adding an Errored(reason) state to the sim callback.
> Sim: Missing Error State

- core/cu29_soa_derive/src/lib.rs
- core/cu29_soa_derive/tests/proctest.rs
While SOAs are fixed length in the Copperlist, this adds a way to partially fill them.
It also shorten the serialization len.
> Adds variable length to SOAs

- .github/workflows/general.yml
- components/sinks/cu_rp_sn754410/tests/sn754410_tester.rs
- components/sources/cu_ads7883/tests/ads7883_tester.rs
This ensures we have the maximum possible test coverage on CI
> Ignore real HW tests and adds test --workspace to CI/CD

- components/monitors/cu_consolemon/src/lib.rs
- components/payloads/cu_sensor_payloads/src/lib.rs
- components/sources/cu_hesai/src/lib.rs
- components/sources/cu_iceoryx2_src/src/lib.rs
- components/sources/cu_vlp16/src/lib.rs
- components/tasks/cu_pid/src/lib.rs
- core/cu29/src/cutask.rs
- core/cu29_clock/src/lib.rs
- core/cu29_derive/src/lib.rs
- examples/cu_rp_balancebot/src/tasks.rs
This is needed to represent messages that contains more than 1 Tov like several images, several IMU measures etc... We will add helpers like range merging, range intersections etc in a separate PRs.
> Introducing CuTimeRange

- README.md
- components/sinks/cu_iceoryx2_sink/src/lib.rs
- components/sinks/cu_lewansoul/src/lib.rs
- components/sinks/cu_rp_gpio/src/lib.rs
- components/sinks/cu_rp_sn754410/src/lib.rs
- components/sinks/cu_rp_sn754410/tests/sn754410_tester.rs
- components/sources/cu_ads7883/src/lib.rs
- components/sources/cu_ads7883/tests/ads7883_tester.rs
- components/sources/cu_hesai/src/lib.rs
- components/sources/cu_iceoryx2_src/src/lib.rs
- components/sources/cu_rp_encoder/src/lib.rs
- components/sources/cu_vlp16/src/lib.rs
- components/sources/cu_wt901/src/lib.rs
- components/sources/cu_wt901/tests/wt901_tester.rs
- components/tasks/cu_aligner/README.md
- components/tasks/cu_aligner/src/lib.rs
- components/tasks/cu_pid/src/lib.rs
- core/cu29/src/curuntime.rs
- core/cu29/src/cutask.rs
- core/cu29/src/simulation.rs
- core/cu29_derive/src/lib.rs
- examples/cu_caterpillar/src/tasks.rs
- examples/cu_monitoring/src/main.rs
- examples/cu_multisources/src/tasks.rs
- examples/cu_rp_balancebot/src/tasks.rs
- templates/cu_full/src/tasks.rs
It split artificially the implementation of tasks and couples the passed types.
> Removes the lifecycle trait

- core/cu29_derive/src/lib.rs
- core/cu29_derive/src/utils.rs
- examples/cu_rp_balancebot/Cargo.toml
- examples/cu_rp_balancebot/src/resim.rs
This allows our users to symbolically get the output of a given tasks without guessing the execution order that can change from Copper.
> Maps Copperlist indices to named output from tasks.

- core/cu29_helpers/tests/end2end.rs
Compilation issue with
`cargo build --release --all-targets --workspace`
fixed by importing log_debug_mode for debug mode, and importing log for release mode
> [FIX] end2end test of cu29_helpers

- templates/cu_full/Cargo.toml.template
I used `cunew` to generate a new project and hit a couple issues but this one is the one that makes most sense to fix.
I have a bit of an odd setup here. My user-side repo at `$HOME/Repos/scratchpad` and my Cargo workspace root is at `$HOME/Repos/scratchpad/car`. In my workspace, I just add all the crates in my project as members so I can build everything easily.
When I ran cunew, I ran it from the templates dir in my local copper repo, so this:
```bash
cd ~/Repos/copper-rs/templates
cargo cunew ~/Repos/scratchpad/car/copper
```
When I built my code from the workspace root or the new copper project, I got this error
```bash
mike@fedora:copper $ cargo b
error: multiple workspace roots found in the same workspace:
/home/mike/Repos/scratchpad/car/copper/car
/home/mike/Repos/scratchpad/car …
```
> Exclude [workspace] from cunew-generated toml

- Cargo.toml
- core/cu29_derive/src/lib.rs
- core/cu29_runtime/src/config.rs
- core/cu29_unifiedlog/src/lib.rs
- examples/cu_logging_size/Cargo.toml
- examples/cu_logging_size/build.rs
- examples/cu_logging_size/copperconfig.ron
- examples/cu_logging_size/src/main.rs
One for to override the section size (if the copperlist references allocated stuff outside of it) and one for the slab size (that will be hooked up after the construction from the copper_ctx is merged)
> Logging parameters in the Ron file. Fixes #183

- core/cu29_derive/src/lib.rs
- core/cu29_helpers/Cargo.toml
- core/cu29_helpers/src/lib.rs
- core/cu29_runtime/Cargo.toml
- core/cu29_runtime/src/curuntime.rs
- examples/cu_caterpillar/src/main.rs
- examples/cu_iceoryx2/src/bin/downstream.rs
- examples/cu_iceoryx2/src/bin/upstream.rs
- examples/cu_monitoring/src/main.rs
- examples/cu_multisources/src/main.rs
- examples/cu_pointclouds/src/main.rs
- examples/cu_rp_balancebot/src/main.rs
- examples/cu_rp_balancebot/src/resim.rs
- examples/cu_rp_balancebot/src/sim.rs
This is the draft PR to discuss the changes in the issue #135 
I have made commits to add both the builder pattern and a "new_with_context" method. I did both because I'm not sure which one is actually better, I like the ergonomics of the builder pattern(and it was nice to write), but I like the simplicity of new_with_context 😅. When it's decided which one it's better, I will remove the other one.
I also updated the balance bot example to use the builder pattern, to show how it's used both in the sim_mode and non sim_mode.
I can update the other examples when the changes are settled.
> make the copper app buildable from a CopperContext

- examples/cu_rp_balancebot/src/world/mod.rs
Previously, dragging the cart from one side of the cart will cause the cart to move in opposite direction.
Introducing the camera transform query to fix the drag direction according to the camera view.
> [FIX] (cu_rp_balancebot) fix drag direction for any camera view

- examples/cu_rp_balancebot/Cargo.toml
- examples/cu_rp_balancebot/src/world/mod.rs
- Created a fork in my personal account in order to support bevy 0.15.1 for iyes_perf_ui : https://github.com/IyesGames/iyes_perf_ui/compare/main...makeecat:iyes_perf_ui:main
- Use PerfUiAllEntries instead of PerfUiCompleteBundle
- Tested under cu_rp_balancebot folder:
`cargo run --bin balancebot-sim --release --features perf-ui`
> [FIX] (cu_rp_balancebot) perf-ui feature

- .github/workflows/general.yml
This PR address the issue of `No space left on device (os error 28)` error when running CI which I posted on [Discord](https://discord.com/channels/1305916875741597826/1316747923454951425/1327636394063040634) and also improves the performace significantly as now the action take <ins>**7m 34s**</ins> as opposed to **29m 12s**.
> Fix `No space left on device (os error 28)` and improve CI speed

- .config/_typos.toml
- .config/nextest.toml
- .github/workflows/general.yml
1. split CI into build and test, with matrix of debug and release mode
2. use nextest for parallel testing, configure three package tests that require binding to the same address with serial testing mode in .config/nextest.toml
3. add project generation test back in test matrix.
4. add typos check
5. rust-cache is effective
> [FEAT] add nextest / project generation test / typos check for CI

- core/cu29_derive/Cargo.toml
- core/cu29_derive/build.rs
- core/cu29_derive/src/lib.rs
- core/cu29_derive/tests/compile_fail/copper_runtime/invalid_attribute.rs
- core/cu29_derive/tests/compile_fail/copper_runtime/invalid_attribute.stderr
- core/cu29_derive/tests/compile_fail/copper_runtime/invalid_config_file.rs
- core/cu29_derive/tests/compile_fail/copper_runtime/invalid_config_file.stderr
- core/cu29_derive/tests/compile_fail/copper_runtime/invalid_file_path.rs
- core/cu29_derive/tests/compile_fail/copper_runtime/invalid_file_path.stderr
- core/cu29_derive/tests/compile_fail/cu_msg/invalid_attribute.rs
- core/cu29_derive/tests/compile_fail/cu_msg/invalid_attribute.stderr
- core/cu29_derive/tests/compile_fail/cu_msg/invalid_config_file.rs
- core/cu29_derive/tests/compile_fail/cu_msg/invalid_config_file.stderr
- core/cu29_derive/tests/compile_fail/cu_msg/invalid_file_path.rs
- core/cu29_derive/tests/compile_fail/cu_msg/invalid_file_path.stderr
- core/cu29_derive/tests/compile_fail/cu_msg/non_existent_id.rs
- core/cu29_derive/tests/compile_fail/cu_msg/non_existent_id.stderr
- core/cu29_derive/tests/compile_fail/cu_msg/non_existent_message.rs
- core/cu29_derive/tests/compile_fail/cu_msg/non_existent_message.stderr
- core/cu29_derive/tests/compile_fail/cu_msg/non_existent_task_type.rs
- core/cu29_derive/tests/compile_fail/cu_msg/non_existent_task_type.stderr
- core/cu29_derive/tests/config/invalid_config.ron
- core/cu29_derive/tests/config/non_existent_id.ron
- core/cu29_derive/tests/config/non_existent_message.ron
- core/cu29_derive/tests/config/non_existent_task_type.ron
- core/cu29_runtime/src/config.rs
Fixes #154 
This PR also makes error with RON files much helpful as it not shows, where the error. The following is the error message generated with mistake in RON file
```
error: proc macro panicked
--> examples/cu_caterpillar/src/logreader.rs:4:1
|
4 | gen_cumsgs!("copperconfig.ron");
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: message: Syntax Error in config: Expected string at position 4:17
```
> Catalog and catch the main proc macro usage error

- .github/workflows/general.yml
- core/cu29_helpers/Cargo.toml
- core/cu29_helpers/tests/end2end.rs
1. Add matrix.mode in cache key. Default cache key cause conflict when build/release try to save the same cache key.
2. Further simplify the CI, test all features directly.
3. Addressed dependency security issue of cu29_helpers thanks to cargo audit. Use tempfile instead of tempdir. The tempdir was merged into tempfile and became unmaintained.
> [FIX] (CI) rust-cache key and fix audit

- core/cu29_derive/src/lib.rs
- core/cu29_derive/tests/compile_fail/copper_runtime/invalid_config_path.rs
- core/cu29_derive/tests/compile_fail/copper_runtime/invalid_config_path.stderr
- core/cu29_derive/tests/compile_fail/copper_runtime/invalid_file_path.stderr
- core/cu29_derive/tests/compile_fail/copper_runtime/invalid_logging_config.rs
- core/cu29_derive/tests/compile_fail/copper_runtime/invalid_logging_config.stderr
- core/cu29_derive/tests/compile_fail/cu_msg/invalid_file_path.rs
- core/cu29_derive/tests/compile_fail/cu_msg/invalid_file_path.stderr
- core/cu29_derive/tests/compile_fail/cu_msg/invalid_logging_config.rs
- core/cu29_derive/tests/compile_fail/cu_msg/invalid_logging_config.stderr
- core/cu29_derive/tests/config/invalid_logging_config.ron
- core/cu29_runtime/src/config.rs
Fixes #205 
Also, I Fixed incorrect documentation for `read_configuration_str` as it reads from the String not the file [5c9d82](https://github.com/as1100k-forks/copper-rs/commit/5c9d8242148851d51ea6c2568e7cd15013e91bbb)
> Improve the logging parameters user friendiness

- Cargo.toml
- components/sinks/cu_rp_gpio/Cargo.toml
- components/sources/cu_v4l/Cargo.toml
- core/cu29_runtime/Cargo.toml
- examples/cu_caterpillar/Cargo.toml
- examples/cu_config_variation/Cargo.toml
- examples/cu_rp_balancebot/Cargo.toml
Fix machete in the following crates and passed with this PR: https://github.com/copper-project/copper-rs/pull/224
using `cargo machete`
- cu_config_variation
- cu29_runtime
- cu_rp_gpio
- cu_v4l
- cu_caterpillar
- cu_config_variation
- cu_rp_balancebot
Since machete can cause false positive easily, I suggest we do not add machete in weekly CI.
> [CHORE] Fix machete in workspace

- .github/workflows/general.yml
- core/cu29_runtime/Cargo.toml
- core/cu29_runtime/src/pool.rs
1. pool.rs cuda implementation does not build for windows platform in CI (https://github.com/copper-project/copper-rs/actions/runs/12837161641/job/35800273948)
2. the CI does not reflect non-cuda platform setup for linux/windows platform
1. fixed cfg setup in pool.rs
2. separate CI for non-CUDA and CUDA platforms
3. set up features for non-CUDA platforms in CI manually to exclude CUDA feature. In the future, we need to check if there are new features being introduced, which we need to add these feature flags into CI for non-CUDA platform.
> [FIX] pool cuda support for windows platform

- components/monitors/cu_consolemon/src/debug_pane.rs
- components/monitors/cu_consolemon/src/lib.rs
- examples/cu_caterpillar/src/main.rs
- examples/cu_rp_balancebot/src/main.rs
- examples/cu_rp_balancebot/src/resim.rs
- examples/cu_rp_balancebot/src/sim.rs
This PR makes the following behaviour work:
```txt
text_log = True with no cu-consolemon -> dumping in the console like it was doing before
text_log = False -> ONLY structured logging in the main log no text is constructed ever.
text_log = True with cu-consolemon  -> redirect that to the Pane
text_log = False with cu-consolemon  -> by order of preference: message in the Pane, no pane or empty Pane it there is no way to know
compilation in release mode -> text_log = False is forced, I would even compile out the support like I did for the standard console version
```
_As discussed on discord_
as well as also add time to the log shown in cu-consolemon
> Make cu-consolemon debug pane only active if `text_log` is true

- Cargo.toml
- components/sources/cu_v4l/src/lib.rs
- components/sources/cu_v4l/src/v4lstream.rs
- core/cu29_log_runtime/Cargo.toml
- core/cu29_runtime/Cargo.toml
- core/cu29_runtime/src/pool.rs
In this PR, I expose a way to get statistics over the pools + API improvements (signatures, Results etc...)
> Monitoring global for Pools + API enhancements.

- .github/workflows/general.yml
- .github/workflows/weekly.yml
- examples/cu_rp_balancebot/Cargo.toml
- examples/cu_rp_balancebot/README.md
- examples/cu_rp_balancebot/src/world/mod.rs
Fixes #226 
The issue was blocked because `iyes_perf_ui` isn't using `0.15.1` version of bevy in it's `Cargo.toml` but instead using `0.15.0`.
This is not a real blocker for us as mentioned in [Specifying Dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio) of Cargo Guide, the version `0.15.0` is `>=0.15.0`, and `<0.16.0`.
And since, we want to use anything `>=0.15.1`, this is not going to be any issue as Cargo will automatically select the latest version which today is `0.15.3`
> Add `iyes_perf_ui` back

- core/cu29_runtime/Cargo.toml
- core/cu29_runtime/src/config.rs
fix bug with ron@0.10.1
```
error[E0004]: non-exhaustive patterns: `&ron::Number::__NonExhaustive(_)` not covered
--> core/cu29_runtime/src/config.rs:176:31
|
176 |                 let s = match n {
|                               ^ pattern `&ron::Number::__NonExhaustive(_)` not covered
|
note: `ron::Number` defined here
--> /Users/yang/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ron-0.10.1/src/value/number.rs:36:1
|
36  | pub enum Number {
| ^^^^^^^^^^^^^^^
...
53  |     __NonExhaustive(private::Never),
|     --------------- not covered
= note: the matched value is of type `&ron::Number`
= note: `ron::value::number::private::Never` is uninhabited but is not being matched by value, so a wildcard `_` is required
help: ensure that all possible cases are being handled by adding a …
```
> [CHORE] (cu29_runtime) bump ron to 0.10.1 and petgraph to 0.9.1

- core/cu29_derive/build.rs
- core/cu29_log_derive/build.rs
The beta test failed
https://github.com/copper-project/copper-rs/actions/runs/14458010901/job/40575044210
```
= note:    Creating library D:\a\copper-rs\copper-rs\target\tests\trybuild\debug\deps\cu29_log_derive-16eb8fc691887d16.dll.lib and object D:\a\copper-rs\copper-rs\target\tests\trybuild\debug\deps\cu29_log_derive-16eb8fc691887d16.dll.exp␍
liblmdb_sys-702af18a9ef60260.rlib(535b1ff7273e4654-mdb.o) : error LNK2019: unresolved external symbol __imp_InitializeSecurityDescriptor referenced in function mdb_env_setup_locks␍
liblmdb_sys-702af18a9ef60260.rlib(535b1ff7273e4654-mdb.o) : error LNK2019: unresolved external symbol __imp_SetSecurityDescriptorDacl referenced in function mdb_env_setup_locks␍
D:\a\copper-rs\copper-rs\target\tests\trybuild\debug\deps\cu29_log_derive-16eb8fc691887d16.dl …
```
> [FIX] add link advapi32 in cu29_log_derive for beta toolchain

- Cargo.toml
- components/monitors/cu_consolemon/Cargo.toml
- components/payloads/cu_sensor_payloads/Cargo.toml
- components/payloads/cu_spatial_payloads/Cargo.toml
- components/sinks/cu_lewansoul/Cargo.toml
- components/sinks/cu_msp_sink/Cargo.toml
- components/sources/cu_gstreamer/Cargo.toml
- components/sources/cu_hesai/Cargo.toml
- components/sources/cu_livox/Cargo.toml
- components/sources/cu_msp_src/Cargo.toml
- components/sources/cu_rp_encoder/Cargo.toml
- components/sources/cu_v4l/Cargo.toml
- components/tasks/cu_aligner/Cargo.toml
- components/tasks/cu_apriltag/Cargo.toml
- core/cu29_log/Cargo.toml
- core/cu29_log_runtime/Cargo.toml
- core/cu29_runtime/Cargo.toml
- core/cu29_value/Cargo.toml
- examples/cu_caterpillar/Cargo.toml
- examples/cu_pointclouds/Cargo.toml
- examples/cu_rp_balancebot/Cargo.toml
- examples/cu_standalone_structlog/Cargo.toml
- templates/cu_full/Cargo.toml.template
1. bump cudarc from 0.15.0 to 0.16.0 https://github.com/coreylowman/cudarc/compare/v0.15.0...v0.16.0
2. bump libmacchina from 8.0.0 to 8.1.0 https://github.com/Macchina-CLI/libmacchina/compare/8.0.0...v8.1.0
3. bump circular-buffer from 1.0.0 to 1.1.0 https://github.com/andreacorbellini/rust-circular-buffer/compare/v1.0.0...v1.1.0
4. bump ordered-float from 4.5.0 to 5.0.0 https://github.com/reem/rust-ordered-float/compare/v4.5.0...v5.0.0
> [CHORE] bump dependencies

- components/monitors/cu_consolemon/src/lib.rs
- core/cu29_derive/src/lib.rs
- core/cu29_runtime/src/config.rs
- core/cu29_runtime/src/curuntime.rs
- core/cu29_runtime/src/rendercfg.rs
- examples/cu_config_gen/src/main.rs
- examples/cu_config_variation/src/main.rs
Adds a more flexible way to compose copper configurations sub graphs and build missions (or think about modes) to have several graphs configured and a way to switch from one to another.
This is an intermediate PR maintaining backward compatibility but adding the notion of mission to the serialization / deserialization of the config + building of the dag.
> [WIP] Adding Missions and Includes

- core/cu29_derive/src/lib.rs
- examples/cu_caterpillar/Cargo.toml
- examples/cu_rp_balancebot/src/resim.rs
- examples/cu_rp_balancebot/src/sim.rs
This is triggered by both #122 and the new mission feature.
Builds a "default" mission for backward compatibility.
Reorganize the generation into a mission submodule
Reorganized the app generation into an App module.
Removed all the very hard to read _Things aliases we had to put in to avoid user code collisions. (#122)
> Runtime generation refactor

- components/common/cu_msp_lib/src/commands.rs
- components/common/cu_msp_lib/src/lib.rs
- components/monitors/cu_consolemon/src/debug_pane.rs
- components/monitors/cu_consolemon/src/sysinfo.rs
- components/sinks/cu_iceoryx2_sink/src/lib.rs
- components/sinks/cu_lewansoul/src/lib.rs
- components/sources/cu_hesai/src/lib.rs
- components/sources/cu_hesai/src/parser.rs
- components/sources/cu_iceoryx2_src/src/lib.rs
- components/sources/cu_livox/src/lib.rs
- components/sources/cu_livox/src/parser.rs
- components/sources/cu_v4l/src/lib.rs
- components/sources/cu_v4l/src/v4lstream.rs
- core/cu29_derive/src/lib.rs
- core/cu29_runtime/src/config.rs
- core/cu29_runtime/src/curuntime.rs
- core/cu29_runtime/src/pool.rs
- core/cu29_runtime/src/rendercfg.rs
- core/cu29_value/src/bdec.rs
- core/cu29_value/src/de.rs
- core/cu29_value/src/lib.rs
- examples/cu_logging_size/src/main.rs
- examples/cu_rp_balancebot/src/resim.rs
- examples/cu_rp_balancebot/src/sim.rs
- examples/cu_rp_balancebot/src/tasks.rs
- examples/cu_rp_balancebot/src/world/mod.rs
This PR fixes nightly clippy warnings by updating various formatting macros to use the new inline interpolation syntax. The key changes include:
- Replacing format strings using positional formatting (e.g. "{}") with inline named interpolation (e.g. "{var}").
- Updating error messages, debug prints, and panic messages across multiple modules for consistency.
> [FIX] nightly clippy for format

- components/tasks/cu_dynthreshold/Cargo.toml
- examples/cu_rp_balancebot/Cargo.toml
To pass test with different combination of features flag
```
cargo install cargo-hack
cargo hack check --feature-powerset --workspace
```
We found:
1. resim.rs of `cu_rp_balancebot` used `cu29_export`
2. If `cu_gstreamer` was built without the `gst` flag, and we want to build `cu_dynthreshold` with the `gst` flag, compilation failed (both require the gst flag to be enabled).
This PR fixed both issues and passed the feature-powerset test.
> [FIX] resim needs cu29-export, dynthreshold needs gst flagged gstreamer

- templates/cu_full/bin/cl
- templates/cu_full/bin/log
The current template generate log under `logs` folder, the helper bins were not updated for that.
Update the helper bins to use the copper log under `logs` folder.
> [FIX] fix logs path for template helper bin

- .github/workflows/general.yml
- .github/workflows/weekly.yml
- components/sources/cu_v4l/src/lib.rs
- core/cu29/Cargo.toml
- core/cu29_export/src/lib.rs
- core/cu29_helpers/tests/end2end.rs
- core/cu29_log/README.md
- core/cu29_log/src/lib.rs
- core/cu29_log_derive/Cargo.toml
- core/cu29_log_derive/src/lib.rs
- core/cu29_log_runtime/src/lib.rs
- core/cu29_runtime/src/log.rs
- core/cu29_runtime/src/monitoring.rs
This PR introduces compile-time log level filtering into the Copper logging system. The changes update the logging macros, add a log level field into CuLogEntry, adjust serialization/deserialization, and update documentation and tests accordingly.
- Integrated compile-time log level features and updated logging macros.
- Updated CuLogEntry to include and handle log levels in its constructor, encoding/decoding, and formatting.
- Revised documentation and tests to reflect the new logging level functionalities.
We disable all log macro by default, the user should use related features when importing `cu29` to enable specific log level.
```
[dependencies]
cu29 = { version = "0.7.0", features = ["log-level-debug"] }
```
Detailed instructions are updated in `cu29_log/README.md`.
> [FEAT] compile-time log-level macro

- core/cu29_log/README.md
specify expected behavior if two log-level feature flags are enabled.
Related PR: #318
> [FIX] (cu29_log) fix README

- components/common/cu_msp_lib/src/structs.rs
This PR added `bincode` feature flag gate for `cu-msp-lib` test
The previous packages cannot be compiled with `--no-default-features` since the test rely on `bincode` feature flag.
```
cargo check --all-targets --no-default-features -p cu-msp-lib
```
Add `bincode` feature flag gate for the test
> [FIX] (cu-msp-lib) add bincode feature flag gate fortest

- components/sinks/cu_rp_gpio/src/lib.rs
The previous version fail the compilation on macOS without mock feature:
```
cargo check --no-default-features -p cu-rp-gpio
```
Use `hardware` flag instead of simple no `mock` flag to consider non-linux platform
> [FIX] (cu_rp_gpio) hardware flag instead of not mock flag for Mac compabiibility

- components/sinks/cu_rp_gpio/Cargo.toml
- components/sinks/cu_rp_gpio/src/lib.rs
- core/cu29_log_derive/Cargo.toml
- core/cu29_log_derive/src/index.rs
This PR replaces lazy_static! with std::sync::OnceLock, related crates are `cu-rp-gpio` and `cu29-log-derive`.
> [CHORE] replace lazy_static by std::sync::OnceLock

- components/tasks/cu_apriltag/src/lib.rs
- core/cu29_runtime/src/payload.rs
- core/cu29_runtime/tests/payload_test.rs
This PR moves the CuArrayVec from the cu_apriltag component to the cu29_runtime core.
> [CHORE] Move CuArrayVec from cu_apriltag to cu29_runtime

- Cargo.toml
- components/payloads/cu_ros_payloads/Cargo.toml
- components/payloads/cu_ros_payloads/src/builtin.rs
- components/payloads/cu_ros_payloads/src/lib.rs
- components/payloads/cu_ros_payloads/src/sensor_msgs.rs
- components/payloads/cu_ros_payloads/src/std_msgs.rs
- components/sinks/cu_zenoh_ros_sink/Cargo.toml
- components/sinks/cu_zenoh_ros_sink/README.md
- components/sinks/cu_zenoh_ros_sink/build.rs
- components/sinks/cu_zenoh_ros_sink/src/attachment.rs
- components/sinks/cu_zenoh_ros_sink/src/error.rs
- components/sinks/cu_zenoh_ros_sink/src/keyexpr.rs
- components/sinks/cu_zenoh_ros_sink/src/lib.rs
- components/sinks/cu_zenoh_ros_sink/src/liveliness.rs
- components/sinks/cu_zenoh_ros_sink/src/node.rs
- components/sinks/cu_zenoh_ros_sink/src/topic.rs
- examples/cu_zenoh_ros/Cargo.toml
- examples/cu_zenoh_ros/README.md
- examples/cu_zenoh_ros/build.rs
- examples/cu_zenoh_ros/copperconfig.ron
- examples/cu_zenoh_ros/src/main.rs
This PR adds a ROS compatible Zenoh sink to forward data from Copper applications to ROS 2 via the Zenoh middleware (rmw_zenoh).
- Introduces a new sink (cu-zenoh-ros-sink) with full implementation including liveliness, key expression formatting, and configuration handling.
- Adds an example application (cu_zenoh_ros) and updates workspace members and dependencies accordingly.
> [FEAT] Add ROS compatible zenoh sink

- Cargo.toml
This removes this blocker for the release.
> Fixes #312. Gcc 15 compilation for onig.

- examples/ros_caterpillar/README.txt
- examples/ros_caterpillar/run.sh
- examples/ros_caterpillar/src/gpio_caterpillar/src/flip_node.cpp
- examples/ros_caterpillar/src/gpio_caterpillar/src/propagate_node.cpp
It became totally unmanageable outside very narrow releases of Ubuntu from 3 years ago.
> Ported ros-caterpillar to Docker

- components/monitors/cu_consolemon/src/lib.rs
This PR updates the console UI to support arrow key scrolling, complementing the existing hjkl key controls, addressed: https://github.com/copper-project/copper-rs/issues/336
> [CHORE] support arrow key scrolling for console

- support/nix/README.md
- support/nix/flake.nix
This PR enables the nix flake to be compatible with macos and Linux. We can compile the `copper-rs` with `CUDA`, but the mismatched driver between nix environment and host system cause runtime error when we test `copper-rs`.
> [FEAT] support nix flake for both macos and linux

- core/cu29_derive/src/lib.rs
- core/cu29_runtime/src/curuntime.rs
- core/cu29_runtime/src/cutask.rs
- core/cu29_traits/src/lib.rs
This allows to log keyframes at specific intervals to be able to restore the stack at a specific state.
This is really similar to video formats. It allows for example rotating logs, partial logs, debuggers that can jump in time during replay etc..
It was planned all along when we designed the "Freezable" trait.
> Call and logs "keyframes" of the frozen tasks in a separate log stream in the unified logger

- Cargo.toml
- core/cu29_derive/Cargo.toml
- core/cu29_derive/src/lib.rs
- support/cargo_cubuild/Cargo.toml
- support/cargo_cubuild/README.md
- support/cargo_cubuild/src/main.rs
I don't know why it took me a year to finally just implement this :)
**before**
```bash
$ cargo build
error[E0277]: the trait bound `&[u8]: Reader` is not satisfied
--> examples/cu_caterpillar/src/main.rs:6:1
|
6  | #[copper_runtime(config = "copperconfig.ron")]
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Reader` is not implemented for `&[u8]`
|
note: there are multiple different versions of crate `bincode` in the dependency graph
--> /home/gbin/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/bincode-2.0.1/src/de/read.rs:17:1
```
**after**
```bash
$ cargo cubuild
error[E0277]: the trait bound `&[u8]: Reader` is not satisfied
--> examples/cu_caterpillar/src/main.rs:2629:48
|
2629 |             let mut decoder = DecoderImpl::new(slice, config, ());
| …
```
> cargo cubuild to help debug Copper's compilation errors

- core/cu29/Cargo.toml
- core/cu29/src/lib.rs
- examples/cu_rp_balancebot/Cargo.toml
- examples/cu_rp_balancebot/src/main.rs
This avoids log corruption when users don't want to implement a manual loop.
> [BUG] Adds Ctrlc handler to the default run()

- core/cu29_derive/src/lib.rs
- examples/cu_dorabench/src/logreader.rs
This is to not break backward compatibility with existing code.
> Adds back a CuMsgs type alias

- components/sinks/cu_iceoryx2_sink/src/lib.rs
- components/sources/cu_hesai/src/lib.rs
- components/sources/cu_iceoryx2_src/src/lib.rs
- components/sources/cu_livox/src/lib.rs
- components/sources/cu_v4l/src/lib.rs
- components/sources/cu_vlp16/src/lib.rs
- components/tasks/cu_aligner/src/lib.rs
- components/tasks/cu_apriltag/src/lib.rs
- components/tasks/cu_dynthreshold/src/cu_dynthreshold_impl.rs
- components/tasks/cu_ratelimit/src/lib.rs
- core/cu29_derive/src/lib.rs
- core/cu29_runtime/Cargo.toml
- core/cu29_runtime/src/cutask.rs
- core/cu29_runtime/src/simulation.rs
- examples/cu_caterpillar/src/logreader.rs
- examples/cu_multisources/src/tasks.rs
1. this avoids some unwarranted regression in the user codebase
2. it avoids weird specilization issues I ran into trying to add long running tasks
> Reput the CuMsg type alias instead of explicit CuStampData

- core/cu29_runtime/src/config.rs
This was not the right place as is it confusing when 2 cnx from the same tasks are made.
See logging in the task element instead that has been implemented.
> Remove "store" from the connections

- components/monitors/cu_consolemon/src/lib.rs
This was probably there as a quick fix for empty status
Now that the main cause is fixed it was crashing cu-monitor.
> Fix: cu-monitor crashes on correctly formed empty status message 🤦

- core/cu29_derive/src/lib.rs
I noticed when I was implementing resimulation for my project that the get_taskname_output() methods had the wrong return type, for example:
```rust
default::SimStep::MotorCtrl(CuTaskCallbackState::Process(_, output)) => {
*output = msgs.get_motor_ctrl_output().clone();
SimOverride::ExecutedBySim
}
```
```
|
133 |                 *output = msgs.get_motor_ctrl_output().clone();
|                 -------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `CuStampedData<(), CuMsgMetadata>`, found `CuStampedData<CuGstBuffer, CuMsgMetadata>`
|                 |
|                 expected due to the type of this binding
|
= note: expected struct `cu29::prelude::CuStampedData<(), _>`
found struct `cu29::prelude::CuStampedData<cu_gstreamer::CuGstBuffer, _>`
```
So I did some digging and found out …
> Fix the output type on the get_<taskname>_output() methods

- examples/cu_rp_balancebot/src/world/mod.rs
These are the changes from #439 other than the integration test and comment changes, namely:
- Consolidated the logic for dragging the cart and the rod into one place, separated into one observer for the drag and one for the drag ending. My changes seemed to make the dragging a little smoother since it lets avian handle the position updates instead of directly modifying the transform. It also lets you 'hold' a drag since the previous logic only applied the transform update when the mouse was moved while dragging.
- A few camera control changes, making the camera use real time instead of not specifying (I think `Time` defaults to `Time<Virtual>` where it was being used, meaning e.g. zooming the camera didn't work when time was paused). Also make the camera always face the origin after a …
> Balancebot stability improvement and feature addition

- Cargo.toml
- core/cu29_clock/Cargo.toml
- core/cu29_clock/README.md
- core/cu29_clock/src/lib.rs
- core/cu29_log_runtime/Cargo.toml
This included the removal of the quanta dependency that I wanted to do for a long time.
Now all the counters for the supported platforms are direct in assembly. We keep around some wrapped types for backward compatibility.
> Make cu29-clock no-std compliant

- core/cu29_traits/Cargo.toml
- core/cu29_traits/src/lib.rs
Rather brutal, we will iterate on it to restore the "new_with_cause" functionality.
> Direct no-std port of cu29_traits
